version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  wed-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"